Repository juju/python-libjuju, pull requests merged in 2021-09, with the labels that each got.

#533 Fix issue 532: Set the default_series properly
  juju/bundle.py
  tests/integration/oci-image-charm-no-series/dispatch
  tests/integration/oci-image-charm-no-series/metadata.yaml
  tests/unit/test_bundle.py
Labels: PR: issue fix

#541 a random small bug fix
  juju/model.py
Labels: PR: bug fix

#540 Allow ApplicationFacade set_config with non-string values
  juju/application.py
  tests/integration/test_application.py
  tests/unit/test_bundle.py
Labels: PR: issue fix

#542 Skip macaroon tests issue 534
  tests/integration/test_macaroon_auth.py
Labels: PR: issue fix

#539 Fix issue 530: Check the controller for unsynched models
  juju/client/connector.py
  tests/integration/test_model.py
Labels: PR: issue fix

#546 bring juju/juju.py into life
  juju/application.py
  juju/juju.py
  juju/model.py
  tests/integration/test_juju.py
Labels: enhancement, PR: issue fix
