Repository juju/python-libjuju, pull requests merged in 2023-07, with the labels that each got.

#896 [JUJU-4112] Determining series for local bundle deploying local charm with manifest
  juju/bundle.py
  tests/integration/bundle/local-manifest.yaml
  tests/integration/charm-manifest/config.yaml
  tests/integration/charm-manifest/dispatch
  tests/integration/charm-manifest/manifest.yaml
  tests/integration/charm-manifest/metadata.yaml
  tests/integration/test_model.py
Labels: bug fix, 2.9, forward port

#894 [JUJU-3998] Pass through local_refresh if refreshing with local charm & resources
  juju/application.py
  tests/integration/test_application.py
  tests/integration/test_model.py
  tests/utils.py
Labels: bug fix, 2.9

#897 [JUJU-4113] Release 2.9.43.0 notes
  VERSION
  docs/changelog.rst
  tests/integration/test_application.py
Labels: 2.9, release

#899 Stabilize sphinx build on RTD
  .readthedocs.yaml
  CONTRIBUTORS
  Makefile
  docs/narrative/application.rst
  docs/narrative/controller.rst
  docs/narrative/model.rst
  docs/readme.rst
  docs/requirements.txt
  tox.ini
Labels: backward port, docs

#901 [JUJU-4110] `charm_name` on Application object
  juju/application.py
  tests/integration/test_application.py
Labels: 2.9, forward port

#902 [JUJU-4204] Model.name on 2.9
  juju/model.py
  tests/integration/test_model.py
Labels: 2.9

#907 [JUJU-4048] Use GetChangesMapArgs for bundle changes
  juju/bundle.py
  tests/integration/test_crossmodel.py
  tests/integration/test_model.py
  tests/unit/test_bundle.py
Labels: 3.2

#905 [JUJU-4231] wait_for_idle to consider app status
  juju/model.py
  tests/integration/test_model.py
  tests/unit/test_model.py
Labels: bug fix, 2.9, forward port

#911 Stabilize sphinx doc builds for `2.9` track
  .readthedocs.yaml
  CONTRIBUTORS
  Makefile
  docs/_extensions/automembersummary.py
  docs/api/juju.cloud.rst
  docs/conf.py
  docs/narrative/application.rst
  docs/narrative/controller.rst
  docs/narrative/model.rst
  docs/readme.rst
  docs/requirements.txt
  tox.ini
Labels: enhancement, 2.9

#912 Add pytest.ini to register custom pytest marks
  .pytest.ini
Labels: 2.9, forward port

#916 Removing Upper Constraint
  setup.py
Labels: 2.9, forward port

#919 [JUJU-4297] Release 2.9.44.0 notes
  VERSION
  docs/changelog.rst
Labels: 2.9, release

#920 [JUJU-4298] Release 3.2.0.1 notes
  VERSION
  docs/changelog.rst
Labels: 3.2, release

#921 Cleanup release process
  Makefile
  docs/readme.rst
  setup.py
Labels: 2.9, forward port, maintenance

#922 Repository Maintenance Improvements
  .github/ISSUE_TEMPLATE/BugReport.yml
  .github/ISSUE_TEMPLATE/FeatureRequest.yml
  .github/workflows/stale.yaml
  docs/CONTRIBUTING.md
Labels: maintenance

#926 Stale bot to not bother feature requests
  .github/workflows/stale.yaml
Labels: maintenance
