Repository juju/python-libjuju, pull requests merged in 2023-10, with the labels that each got.

#957 Deploy by revision on 2.9
  examples/annotate.py
  examples/deploy_with_revision.py
  juju/model.py
  tests/integration/test_model.py
Labels: enhancement, 2.9

#960 Application refresh with resources
  juju/application.py
  juju/utils.py
  tests/integration/test_application.py
Labels: 2.9, forward port

#964 Improve jujudata to find controller name by endpoint
  juju/client/connector.py
  juju/client/jujudata.py
  juju/errors.py
Labels: 2.9, forward port

#966 Find controller name by endpoint on 3.x track
  juju/client/connector.py
  juju/client/jujudata.py
  juju/errors.py
Labels: 3.x

#968 Allow switch kwarg in refresh to switch to local charms
  juju/application.py
  tests/integration/test_application.py
  tests/unit/test_application.py
Labels: 2.9, forward port

#969 Parse charm URLs consistantly for local charms
  juju/bundle.py
  juju/model.py
  juju/url.py
  tests/unit/test_url.py
Labels: 2.9, forward port

#971 Allow switch kwarg in refresh to switch to local charms
  juju/application.py
  tests/integration/test_application.py
  tests/unit/test_application.py
Labels: 3.x

#975 Fix juju config directory location pointed by XDG_DATA_HOME
  juju/utils.py
Labels: 2.9, forward port

#976 Juju config directory location fix on 3.x
  juju/utils.py
Labels: 3.x

#977 [JUJU-4779] Switch to local properly
  examples/local_refresh.py
  juju/application.py
  tests/integration/test_application.py
Labels: 2.9, forward port

#978 [JUJU-4779] Ensure valid charm origin for local charm switches
  examples/local_refresh.py
  juju/application.py
  tests/integration/test_application.py
Labels: 3.x

#973 Application refresh with resources on 3.x
  juju/application.py
  juju/utils.py
  tests/integration/test_application.py
Labels: 3.x

#979 Release 2.9.45.0 notes
  VERSION
  docs/changelog.rst
Labels: 2.9, release

#980 Release 3.2.3.0 notes
  docs/changelog.rst
Labels: release, 3.x

#982 Bump up the version number to 3.2.3.0
  VERSION
Labels: release, 3.x
