Repository juju/python-libjuju, pull requests merged in 2023-11, with the labels that each got.

#984 Free pyblijuju from relying on juju client when connecting to a controller
  juju/client/connector.py
  juju/controller.py
  juju/model.py
  tests/integration/test_controller.py
Labels: bug, 3.x

#937 Handle FileNotFoundError on current_controller()
  juju/client/connector.py
  juju/client/jujudata.py
  juju/errors.py
  tests/unit/test_jujudata.py
Labels: 3.x

#986 Add support for adding user secrets
  .github/workflows/test.yaml
  .github/workflows/test_candidate.yaml
  .github/workflows/test_edge.yaml
  juju/client/_client.py
  juju/client/_client1.py
  juju/client/_client19.py
  juju/client/_client2.py
  juju/client/_client7.py
  juju/client/_definitions.py
  juju/client/connection.py
  juju/client/schemas-juju-3.3.0.json
  juju/errors.py
  juju/model.py
  juju/secrets.py
  tests/integration/charm-base-charmcraft-yaml/manifest.yaml
  tests/integration/test_application.py
  tests/integration/test_model.py
  tests/integration/test_secrets.py
  tests/unit/test_secrets.py
Labels: 3.x

#987 Complete support for user secrets
  juju/model.py
  tests/integration/test_secrets.py
Labels: 3.x

#988 Release 3.3.0.0 notes
  VERSION
  docs/changelog.rst
Labels: release, 3.x
